path = '/workspaces/dream-wedding/backend/server.js'
with open(path, 'r') as f:
    content = f.read()

old_anchor = "// GET /api/v2/vendor/calendar.ics/:vendorId — iCal feed for Apple/Google Calendar"

new_import = (
"// POST /api/v2/vendor/calendar/import/:vendorId — parse .ics and block dates in TDW\n"
"app.post('/api/v2/vendor/calendar/import/:vendorId', async (req, res) => {\n"
"  try {\n"
"    const { vendorId } = req.params;\n"
"    const { ics_content } = req.body;\n"
"\n"
"    if (!ics_content) return res.status(400).json({ success: false, error: 'No iCal content provided.' });\n"
"\n"
"    // Parse VEVENT blocks\n"
"    const events = [];\n"
"    const eventBlocks = ics_content.split('BEGIN:VEVENT');\n"
"    for (let i = 1; i < eventBlocks.length; i++) {\n"
"      const block = eventBlocks[i];\n"
"\n"
"      // Extract fields using indexOf/slice — no regex needed\n"
"      function extractField(blk, field) {\n"
"        const prefix = field + ':';\n"
"        const idx = blk.indexOf(prefix);\n"
"        if (idx === -1) return null;\n"
"        const start = idx + prefix.length;\n"
"        const end = blk.indexOf('\\n', start);\n"
"        return end === -1 ? blk.slice(start).trim() : blk.slice(start, end).trim().replace(/\\r$/, '');\n"
"      }\n"
"\n"
"      // Also handle DTSTART with params like DTSTART;VALUE=DATE:20250614\n"
"      function extractDtStart(blk) {\n"
"        const idx = blk.indexOf('DTSTART');\n"
"        if (idx === -1) return null;\n"
"        const colon = blk.indexOf(':', idx);\n"
"        if (colon === -1) return null;\n"
"        const end = blk.indexOf('\\n', colon);\n"
"        const raw = end === -1 ? blk.slice(colon + 1).trim() : blk.slice(colon + 1, end).trim().replace(/\\r$/, '');\n"
"        return raw.slice(0, 8); // just YYYYMMDD\n"
"      }\n"
"\n"
"      function extractDtEnd(blk) {\n"
"        const idx = blk.indexOf('DTEND');\n"
"        if (idx === -1) return null;\n"
"        const colon = blk.indexOf(':', idx);\n"
"        if (colon === -1) return null;\n"
"        const end = blk.indexOf('\\n', colon);\n"
"        const raw = end === -1 ? blk.slice(colon + 1).trim() : blk.slice(colon + 1, end).trim().replace(/\\r$/, '');\n"
"        return raw.slice(0, 8);\n"
"      }\n"
"\n"
"      function toDateStr(yyyymmdd) {\n"
"        if (!yyyymmdd || yyyymmdd.length < 8) return null;\n"
"        return yyyymmdd.slice(0, 4) + '-' + yyyymmdd.slice(4, 6) + '-' + yyyymmdd.slice(6, 8);\n"
"      }\n"
"\n"
"      const rawStart = extractDtStart(block);\n"
"      const rawEnd = extractDtEnd(block);\n"
"      const summary = extractField(block, 'SUMMARY');\n"
"      const status = extractField(block, 'STATUS');\n"
"\n"
"      if (!rawStart) continue;\n"
"      if (status === 'CANCELLED') continue;\n"
"\n"
"      const startStr = toDateStr(rawStart);\n"
"      if (!startStr) continue;\n"
"\n"
"      if (rawEnd && rawEnd !== rawStart) {\n"
"        const endStr = toDateStr(rawEnd);\n"
"        const cur = new Date(startStr);\n"
"        const endDate = new Date(endStr);\n"
"        while (cur < endDate) {\n"
"          const y = cur.getFullYear();\n"
"          const m = String(cur.getMonth() + 1).padStart(2, '0');\n"
"          const d = String(cur.getDate()).padStart(2, '0');\n"
"          events.push({ date: y + '-' + m + '-' + d, note: summary });\n"
"          cur.setDate(cur.getDate() + 1);\n"
"        }\n"
"      } else {\n"
"        events.push({ date: startStr, note: summary });\n"
"      }\n"
"    }\n"
"\n"
"    if (events.length === 0) {\n"
"      return res.json({ success: true, imported: 0, message: 'No events found in this calendar file.' });\n"
"    }\n"
"\n"
"    // Dedupe against existing\n"
"    const { data: existing } = await supabase\n"
"      .from('vendor_availability_blocks')\n"
"      .select('blocked_date')\n"
"      .eq('vendor_id', vendorId);\n"
"\n"
"    const existingSet = new Set((existing || []).map(function(e) { return e.blocked_date; }));\n"
"\n"
"    const toInsert = events\n"
"      .filter(function(e) { return !existingSet.has(e.date); })\n"
"      .map(function(e) { return {\n"
"        vendor_id: vendorId,\n"
"        blocked_date: e.date,\n"
"        note: e.note ? 'Imported: ' + e.note.slice(0, 100) : 'Imported from calendar',\n"
"      }; });\n"
"\n"
"    if (toInsert.length === 0) {\n"
"      return res.json({ success: true, imported: 0, message: 'All dates already exist in your TDW calendar.' });\n"
"    }\n"
"\n"
"    const { error } = await supabase.from('vendor_availability_blocks').insert(toInsert);\n"
"    if (error) throw error;\n"
"\n"
"    res.json({ success: true, imported: toInsert.length, total_parsed: events.length });\n"
"\n"
"  } catch (err) {\n"
"    console.error('[iCal import]', err.message);\n"
"    res.status(500).json({ success: false, error: err.message });\n"
"  }\n"
"});\n"
"\n"
"// GET /api/v2/vendor/calendar.ics/:vendorId — iCal feed for Apple/Google Calendar"
)

assert content.count(old_anchor) == 1, "anchor not found exactly once"
content = content.replace(old_anchor, new_import, 1)
print("OK: iCal import endpoint added")

with open(path, 'w') as f:
    f.write(content)
print("OK: server.js written")
